apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: frigate-auth-middleware
  namespace: frigate
spec:
  forwardAuth:
    address: http://oauth2-proxy.keycloak.svc.cluster.local/oauth2/auth
    trustForwardHeader: true
    authResponseHeaders:
      - "Authorization"
      - "X-Auth-Request-User"
      - "X-Auth-Request-Email"
