apiVersion: v1
kind: Secret
metadata:
  name: frigate-config-secret
  namespace: frigate
  labels:
    app.kubernetes.io/name: frigate
    app.kubernetes.io/instance: frigate
type: Opaque
data:
  config.yaml: {{ .Values.configContent | default "# Файл config.yaml не передан. Вставьте содержимое через --set-file или обновите values.yaml." | b64enc }}
