replicaCount: 1
image:
  repository: ghcr.io/blakeblackshear/frigate
  pullPolicy: IfNotPresent
  tag: "6936d33-tensorrt"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

# Для использования с NVIDIA GPU
gpu:
  enabled: true
  runtimeClassName: nvidia  # Обязательно для использования с NVIDIA GPU

serviceAccount:
  create: false
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext:
  runAsUser: 0
  runAsGroup: 0

securityContext:
  privileged: true

service:
  type: ClusterIP
  port: 80

storage:
  enabled: true
  size: 800Gi
  storageClass: longhorn-no-replicas
  configSize: 2Gi

sizeLimit: 17048Mi

hwaccel:
  intelEnabled: false
  usbEnabled: false

ingress:
  enabled: true
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/auth-url: "http://traefik-auth.default.svc.cluster.local/api/v1/auth/vouch"
    nginx.ingress.kubernetes.io/auth-signin: "https://auth.rubystay.vn/?continue=https://webcams.rubystay.vn"
    nginx.ingress.kubernetes.io/auth-response-headers: "X-User-Id, X-Auth-User, X-Auth-Email"
  hosts:
    - host: webcams.rubystay.vn
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
resources:
  requests: {}
#    memory: "8Gi"  # Увеличили минимальный запрос памяти
#    cpu: "4"    # Больше CPU для стабильной работы
#    ephemeral-storage: "15Gi"
#  limits:
#    memory: "32Gi"  # Максимум до 32 ГБ
#    cpu: "30"    # До 8 ядер
#    ephemeral-storage: "30Gi"
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

nodeSelector:
  node: pve

tolerations: []

affinity: {}

secrets: []
