replicaCount: 1
image:
  repository: ghcr.io/blakeblackshear/frigate
  pullPolicy: Always
  tag: "0.15.0-beta7-tensorrt"
imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: false
  annotations: {}
  name: ""
podAnnotations: {}
podSecurityContext: {}
securityContext:
  privileged: true
service:
  type: ClusterIP
  port: 80
storage:
  enabled: true
  size: 100Gi
  storageClass: local-path
  configSize: 100Mi
hwaccel:
  intelEnabled: true
  usbEnabled: false
ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: frigate.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
resources: {}
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
nodeSelector: {}
tolerations: []
affinity: {}
secrets: []
cameras:
  example_camera:
    ffmpeg:
      inputs:
        - path: rtsp://username:password@camera_ip:port/stream
          roles:
            - detect
    detect:
      width: 1920
      height: 1080
      fps: 5
mqtt:
  enabled: true
  externalBrokerHostname: ~
